FROM adoptopenjdk:11-jdk-hotspot as builder
WORKDIR /spring_api
COPY . .
RUN ./mvnw clean package -DskipTests
FROM adoptopenjdk:11-jre-hotspot
WORKDIR /spring_api
COPY --from=builder /spring_api/target/spring_api-0.0.1-SNAPSHOT.jar .
CMD ["java", "-jar", "spring_api-0.0.1-SNAPSHOT.jar"]
